### PR TITLE
Removed switch logic and added tests

### PR DESCRIPTION
**Pull request by andreabadesso**
feat(): improved code readability and improved code to be able to dynamically catch metatags instead of mapping every possible combination on switch clauses

### CODE REVIEW

**Comment by nicholasess** [comment]
What do command to execute test?

**Comment by andreabadesso** [comment]
I added the test command to `npm test`, you will need **mocha** installed globally:

`npm install mocha -g`

**Comment by nicholasess** [comment]
Nice @andreabadesso, but with switch cases, the package returned facebook and twitter metatags.
Now return just facebook metatags, can you enable others metatags?

**Comment by andreabadesso** [comment]
@nicholasess tested it here and it's returning twitter metatags, added a test and a mock, can you give me an example of a website that is not working?

**Comment by nicholasess** [comment]
The teste can return ok for the twitter tags, but when i create a file and require file index.js with url "http://99folks.com", just return facebook tags.

```
var tag = require('./index');
var url = 'http://99folks.com';
tag(url, function(err, data){
	console.log(data);
})
```

result
```
{ facebook:
   { title: '99folks',
     description: 'A free and simple social tool to share contacts da
se people.',
     url: 'http://99folks.com',
     site_name: '99folks',
     image: 'http://99folks.com/img/logo-white-bg.jpg',
     type: 'website' } }
```

**Comment by andreabadesso** [comment]
@nicholasess fixed on last commit, didn't notice there could be 'property' and 'name' in a meta tag

**Comment by nicholasess** [comment]
Nice @andreabadesso, the next PR, someone can arrange the objects when return undefined in 'key'.

**Pull request merged**
